version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: fitness-tracker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: HamdiFitness1
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - fitness-network
  
  api:
   build: ./api
   container_name: fitness-tracker-api
   restart: always
   environment:
    DB_HOST: mariadb
    DB_PORT: 3306
    DB_USER: fitness_user
    DB_PASSWORD: user_password
    DB_NAME: fitness_db
   ports:
    - "3000:3000"
   depends_on:
    - mariadb
   networks:
    - fitness-network

volumes:
  mariadb_data:

networks:
  fitness-network:
    driver: bridge